version: '3'

services:
  daemon:
    image: lb-daemon
    container_name: lb-daemon
    build: ./daemon/.
    volumes:
      - proxy_cfg:/app/haproxy:rw
      - /var/run/docker.sock:/var/run/docker.sock
  flask:
    image: flask-image
    container_name: flask-1
    build: ./flask_app/.
  ha_proxy:
    build: ./ha_proxy/.
    container_name: ha_proxy
    ports:
      - "5000:80"
    volumes: 
      - proxy_cfg:/usr/local/etc/haproxy:ro
networks:
    default:
      name: flask-lb
      driver: bridge

volumes:
  proxy_cfg:

